-- MySQL Script generated by MySQL Workbench
-- Sáb 18 Fev 2017 17:36:59 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_newUser
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_newUser` ;

-- -----------------------------------------------------
-- Schema db_newUser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_newUser` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `db_newUser` ;

-- -----------------------------------------------------
-- Table `tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `house_number` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `cellphone` VARCHAR(11) NULL,
  `webpage` VARCHAR(100) NULL,
  `skype` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
