-- MySQL Script generated by MySQL Workbench
-- seg 01 mai 2017 17:28:16 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema modelDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `modelDB` ;

-- -----------------------------------------------------
-- Schema modelDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelDB` DEFAULT CHARACTER SET utf8 ;
USE `modelDB` ;

-- -----------------------------------------------------
-- Table `modelDB`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelDB`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `modelDB`.`tbl_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fullname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelDB`.`tbl_calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelDB`.`tbl_calendar` ;

CREATE TABLE IF NOT EXISTS `modelDB`.`tbl_calendar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `startdate` DATETIME NOT NULL,
  `enddate` DATETIME NULL,
  `location` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelDB`.`tbl_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelDB`.`tbl_note` ;

CREATE TABLE IF NOT EXISTS `modelDB`.`tbl_note` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(50) NOT NULL,
  `body` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelDB`.`tbl_news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelDB`.`tbl_news` ;

CREATE TABLE IF NOT EXISTS `modelDB`.`tbl_news` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(50) NOT NULL,
  `body` VARCHAR(200) NOT NULL,
  `imagePath` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelDB`.`tbl_slide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelDB`.`tbl_slide` ;

CREATE TABLE IF NOT EXISTS `modelDB`.`tbl_slide` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(50) NOT NULL,
  `body` VARCHAR(200) NOT NULL,
  `imagePath` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelDB`.`tbl_candidate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelDB`.`tbl_candidate` ;

CREATE TABLE IF NOT EXISTS `modelDB`.`tbl_candidate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(100) NOT NULL,
  `birthDate` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `registerId` VARCHAR(8) NOT NULL,
  `registerCpf` VARCHAR(11) NOT NULL,
  `registerIdPath` VARCHAR(200) NOT NULL,
  `registerCpfPath` VARCHAR(200) NOT NULL,
  `adressType` ENUM('Residencial', 'Comercial') NOT NULL,
  `adress` VARCHAR(150) NOT NULL,
  `complement` VARCHAR(20) NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `civilServant` TINYINT(1) NULL DEFAULT 0,
  `wantScholarship` TINYINT(1) NULL DEFAULT 0,
  `recommendationLetterPath` VARCHAR(200) NULL,
  `schoolEducation` ENUM('Ensino Fundamental', 'Ensino Médio', 'Ensino Superior', 'Especialização', 'Mestrado', 'Doutorado', 'Pós-Doutorado') NOT NULL,
  `numberOfCourses` ENUM('Nenhum', 'Um a dois', 'Acima de dois') NOT NULL,
  `reasonForEntry` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
